project:
  type: website
  output-dir: docs

website:
  title: "Machine Learning World"
  navbar:
    right:
      - icon: github
        text: "My Github Repository"
        href: https://github.com/abdourahmanbarry/Machine-Learning-World
      - about.qmd
      - icon: github
        href: https://github.com/abdourahmanbarry/Machine-Learning-World
      
format:
  html:
    theme: pulse
    css: styles.css

editor: visual

